(function(){
'use strict';
const CORE=window.PoppyArchiveJourneyCore;if(!CORE)return;
const SETTINGS_URL='https://poppy-auth-api.hosseinasgari898989.workers.dev/api/auth/settings';
const BLOCK_SELECTOR='p,h3,h4,li,.quote';
const S={active:false,paused:false,article:0,block:0,word:0,speed:1,completed:false,timer:null,persistTimer:null,keys:[],metrics:null,store:null,guard:false};
const $=id=>document.getElementById(id);
const lang=()=>{try{return currentLang==='en'?'en':'fa';}catch(_){return'fa';}};
const T=(fa,en)=>lang()==='en'?en:fa;
const authToken=()=>{try{return localStorage.getItem('poppy_auth_token')||'';}catch(_){return'';}};
function source(key){const a=articles&&articles[key];return a?(a[lang()]||a.fa||a.en):null;}
function metrics(){S.keys=[...document.querySelectorAll('.articleCard[data-article]')].map(x=>x.dataset.article);let total=0;S.metrics=S.keys.map(k=>{const box=document.createElement('div');box.innerHTML=(source(k)?.content)||'';const wc=[...box.querySelectorAll(BLOCK_SELECTOR)].map(x=>(x.textContent||'').trim().split(/\s+/).filter(Boolean).length);const words=wc.reduce((a,b)=>a+b,0);total+=words;return{wordCounts:wc,words};});S.metrics.total=total;return S.metrics;}
function makeStore(){return CORE.createProgressStore({storage:localStorage,getAuthToken:authToken,fetchImpl:window.fetch.bind(window),settingsUrl:SETTINGS_URL});}
function pos(){return{article:S.article,block:S.block,word:S.word,speed:S.speed,completed:S.completed};}
function passed(){let n=0;for(let i=0;i<S.article;i++)n+=S.metrics[i].words;const m=S.metrics[S.article];for(let i=0;i<S.block;i++)n+=m.wordCounts[i]||0;return n+S.word;}
function pct(){return Math.min(100,Math.round(passed()/Math.max(1,S.metrics.total)*100));}
function inject(){
 if(!$('archiveJourneyNav')){const grid=document.querySelector('.navgrid');if(grid){const b=document.createElement('button');b.type='button';b.id='archiveJourneyNav';b.className='navcard';b.innerHTML='<span class="aj-icon">✦</span><strong class="aj-title"></strong><small class="aj-sub"></small>';const n=grid.querySelector('[data-target="news"]');n&&n.nextSibling?grid.insertBefore(b,n.nextSibling):grid.appendChild(b);b.onclick=start;}}
 if(!$('archiveJourneyBar')){const b=document.createElement('div');b.id='archiveJourneyBar';b.innerHTML='<div id="archiveJourneyHead"><div id="archiveJourneyHeadMain"><div id="archiveJourneyTitle"></div><div id="archiveJourneyMeta"></div></div><div id="archiveJourneyPct">0%</div></div><div id="archiveJourneyTrack"><div id="archiveJourneyFill"></div></div><div id="archiveJourneyControls"><button class="archiveJourneyBtn" id="ajPause"></button><button class="archiveJourneyBtn" data-aj-speed="0.5">0.5x</button><button class="archiveJourneyBtn" data-aj-speed="1">1x</button><button class="archiveJourneyBtn" data-aj-speed="1.5">1.5x</button><button class="archiveJourneyBtn" data-aj-speed="2">2x</button><button class="archiveJourneyBtn exit" id="ajExit"></button></div>';document.body.appendChild(b);$('ajPause').onclick=togglePause;$('ajExit').onclick=exit;b.querySelectorAll('[data-aj-speed]').forEach(x=>x.onclick=()=>setSpeed(Number(x.dataset.ajSpeed)));}
 if(!$('archiveJourneyResume')){const d=document.createElement('div');d.id='archiveJourneyResume';d.innerHTML='<div id="archiveJourneyResumeBox"><h3></h3><p></p><div id="archiveJourneyResumeActions"><button class="primary" id="ajResume"></button><button id="ajRestart"></button></div></div>';document.body.appendChild(d);$('ajResume').onclick=()=>resume(true);$('ajRestart').onclick=()=>resume(false);}
 if(!$('archiveJourneyToast')){const d=document.createElement('div');d.id='archiveJourneyToast';document.body.appendChild(d);}labels();
}
function labels(){const n=$('archiveJourneyNav');if(n){n.querySelector('.aj-title').textContent=T('حالت مطالعه','Archive Journey');n.querySelector('.aj-sub').textContent=T('مطالعه‌ی خودکار مقاله‌ها','Guided article reading');}if($('ajPause'))$('ajPause').textContent=S.paused?'▶ '+T('ادامه','Resume'):'⏸ '+T('توقف','Pause');if($('ajExit'))$('ajExit').textContent=T('خروج','Exit');if($('ajResume'))$('ajResume').textContent=T('ادامه','Resume');if($('ajRestart'))$('ajRestart').textContent=T('از اول','Start over');}
function toast(m){const x=$('archiveJourneyToast');if(!x)return;x.textContent=m;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),1800);}
function bar(){const d=source(S.keys[S.article])||{};$('archiveJourneyTitle').textContent=d.title||'';$('archiveJourneyMeta').textContent=T('مقاله '+(S.article+1)+' از '+S.keys.length+' • بخش '+(S.block+1),'Article '+(S.article+1)+' of '+S.keys.length+' • Block '+(S.block+1));$('archiveJourneyPct').textContent=pct()+'%';$('archiveJourneyFill').style.width=pct()+'%';document.querySelectorAll('[data-aj-speed]').forEach(x=>x.classList.toggle('active',Number(x.dataset.ajSpeed)===S.speed));labels();}
function clean(){const c=$('articleContent');if(!c)return;c.querySelectorAll('.aj-word').forEach(x=>x.replaceWith(document.createTextNode(x.textContent)));c.querySelectorAll('.aj-current').forEach(x=>x.classList.remove('aj-current'));}
function words(){clean();const c=$('articleContent');if(!c)return;c.querySelectorAll(BLOCK_SELECTOR).forEach(block=>{const w=document.createTreeWalker(block,NodeFilter.SHOW_TEXT),nodes=[];let n;while((n=w.nextNode()))if(n.nodeValue&&n.nodeValue.trim())nodes.push(n);nodes.forEach(tn=>{const f=document.createDocumentFragment();tn.nodeValue.split(/(\s+)/).filter(Boolean).forEach(p=>{if(/^\s+$/.test(p))f.appendChild(document.createTextNode(p));else{const s=document.createElement('span');s.className='aj-word';s.textContent=p;f.appendChild(s);}});tn.replaceWith(f);});});}
function paint(scroll){const bs=[...$('articleContent').querySelectorAll(BLOCK_SELECTOR)];bs.forEach((b,bi)=>{b.classList.toggle('aj-current',bi===S.block);[...b.querySelectorAll('.aj-word')].forEach((w,wi)=>{w.classList.toggle('is-read',bi<S.block||(bi===S.block&&wi<S.word));w.classList.toggle('is-current',bi===S.block&&wi===S.word);});});const w=bs[S.block]?.querySelectorAll('.aj-word')[S.word];if(w&&scroll)w.scrollIntoView({behavior:'smooth',block:'center'});bar();}
function openCurrent(){const k=S.keys[S.article];if(!k)return false;S.guard=true;try{openArticle(k);}finally{S.guard=false;}words();document.body.classList.add('archiveJourneyActive');paint(false);return true;}
function saveLater(){clearTimeout(S.persistTimer);S.persistTimer=setTimeout(()=>{S.persistTimer=null;saveNow(false);},800);}
async function saveNow(keepalive){try{await S.store.save(pos(),{keepalive:!!keepalive});}catch(_){if(authToken())toast(T('⚠️ ذخیره در حساب انجام نشد','⚠️ Account progress could not be saved'));}}
function advance(){const n=CORE.nextPosition(S.article,S.block,S.word,S.metrics);S.article=n.article;S.block=n.block;S.word=n.word;S.completed=n.completed;if(S.completed){finish();return;}openCurrent();saveNow(false);}
function tick(){if(!S.active||S.paused)return;const b=$('articleContent')?.querySelectorAll(BLOCK_SELECTOR)[S.block];if(!b){advance();return;}const ws=b.querySelectorAll('.aj-word');if(!ws.length){advance();return;}S.word++;if(S.word>=ws.length){S.word=0;advance();}else{paint(true);saveLater();}}
function restartTimer(){clearInterval(S.timer);if(S.active&&!S.paused)S.timer=setInterval(tick,Math.max(95,150/S.speed));}
function togglePause(){if(!S.active)return;S.paused=!S.paused;restartTimer();bar();saveNow(false);}
function setSpeed(v){S.speed=CORE.SPEEDS.includes(v)?v:1;restartTimer();bar();saveNow(false);}
function showResume(p){const d=$('archiveJourneyResume');d.querySelector('h3').textContent=T('ادامه‌ی مطالعه؟','Resume reading?');d.querySelector('p').textContent=T('آخرین موقعیت: مقاله '+(p.article+1)+'، بخش '+(p.block+1)+'، کلمه '+(p.word+1),'Last position: article '+(p.article+1)+', block '+(p.block+1)+', word '+(p.word+1));d.classList.add('show');}
function hideResume(){$('archiveJourneyResume')?.classList.remove('show');}
async function resume(yes){hideResume();if(!yes){S.article=0;S.block=0;S.word=0;S.completed=false;await saveNow(false);}S.active=true;S.paused=false;$('archiveJourneyBar').classList.add('show');openCurrent();restartTimer();}
async function start(){if(S.active)return;metrics();S.store=makeStore();let saved=null;try{saved=await S.store.load();}catch(_){toast(T('ذخیره در دسترس نبود؛ از ابتدا شروع شد.','Storage unavailable; starting from the beginning.'));}if(saved&&saved.completed){S.article=0;S.block=0;S.word=0;S.speed=saved.speed||1;S.completed=false;}else if(saved&&(saved.article||saved.block||saved.word)){const p=CORE.normalizeState(saved,S.keys.length,S.metrics[0].wordCounts.length,S.metrics[0].wordCounts[0]||1);Object.assign(S,p);S.completed=false;inject();showResume(S);return;}else{S.article=0;S.block=0;S.word=0;S.speed=saved?.speed||1;S.completed=false;}S.active=true;S.paused=false;inject();$('archiveJourneyBar').classList.add('show');openCurrent();restartTimer();saveNow(false);}
async function exit(){if(!S.active)return;clearInterval(S.timer);clearTimeout(S.persistTimer);await saveNow(true);S.active=false;S.paused=false;clean();document.body.classList.remove('archiveJourneyActive');$('archiveJourneyBar').classList.remove('show');S.guard=true;try{closeArticleModal();}finally{S.guard=false;}toast(T('موقعیت مطالعه ذخیره شد.','Reading position saved.'));}
async function finish(){clearInterval(S.timer);clearTimeout(S.persistTimer);S.active=false;S.completed=true;await saveNow(true);clean();document.body.classList.remove('archiveJourneyActive');$('archiveJourneyBar').classList.remove('show');S.guard=true;try{closeArticleModal();}finally{S.guard=false;}toast(T('مطالعه‌ی همه‌ی مقاله‌ها تمام شد.','All articles completed.'));}
function authChange(){if(S.active)exit();S.store=makeStore();}
function init(){inject();metrics();S.store=makeStore();document.addEventListener('poppy-auth',authChange);document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.active)saveNow(true)});window.addEventListener('pagehide',()=>{if(S.active)saveNow(true)});document.addEventListener('keydown',e=>{if(!S.active)return;if(e.key==='Escape'){e.preventDefault();exit();}else if(e.key===' '&&!/INPUT|TEXTAREA|BUTTON/.test(document.activeElement?.tagName||'')){e.preventDefault();togglePause();}});const modal=$('articleModal');if(modal)new MutationObserver(()=>{if(S.active&&!S.guard&&!modal.classList.contains('show'))setTimeout(()=>{if(S.active)openCurrent();},0)}).observe(modal,{attributes:true,attributeFilter:['class']});const old=window.setLanguage;if(typeof old==='function'&&!old.__archiveJourney){const wrap=function(){const r=old.apply(this,arguments);labels();if(S.active)openCurrent();return r;};wrap.__archiveJourney=true;window.setLanguage=wrap;}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.ArchiveJourney={start,pause:togglePause,exit,setSpeed,getState:()=>({...pos(),active:S.active,paused:S.paused})};
})();